# simple.toml: sample file
address   = "localhost:9754" # listenning address
strict    = true
timeout   = "1h"             # read/accept timeout
datadir   = "/var/foobar/"   # directory to archive data
instances = [+0, -1, 2, 255]
maintainer = {
  name = "midbel",
  email = "midbel@foobar.org",
}

# [maintainer]
# name = "midbel"
# email = "midbel@foobar.org"

# server/client configuration
[certificate]
type     = "x509"
location = "/var/foobar/tls/"
server   = "foobar.org"
policy   = "verify"
insecure = false
# before   = 2018-01-01T00:00:00Z
# after    = 2019-01-01T00:00:00Z
#
[[workers]]
name    = "hk"
group   = "239.192.0.1:31002"
apid    = 906
sources = []
location = "/var/foobar/data/906"
every   = 3600
auto    = true

[[workers]]
name    = "hk-foo"
group   = "239.192.0.1:31002"
apid    = 907
sources = [31255001, 31255002, ]
location = "/var/foobar/data/907/hk"
every   = 60
auto    = true

[[workers]]
name    = "sc-foo"
group   = "239.192.0.1:31002"
apid    = 907
sources = [31255101, 31255102, ]
location = "/var/foobar/data/907/sc"
every   = 60
auto    = true

[[workers]]
name    = "hk-bar"
group   = "239.192.0.1:31002"
apid    = 908
sources = [31255003, 31255004, 31255005]
location = "/var/foobar/data/908/hk"
every   = 300
auto    = true

[[workers]]
name    = "sc-bar"
group   = "239.192.0.1:31002"
apid    = 908
sources = [31255103, 31255104, 31255105]
location = "/var/foobar/data/908/sc"
every   = 300
auto    = true

[[logger]]
name = "hello"

  [logger.rotate]
  location   = "/var/log/hello"
  keep       = 7
  compressed = true

  [[logger.journal]]
  type = "memory"

  [[logger.journal]]
  type = "file"

[[logger]]
name = "world"

  [logger.rotate]
  location   = "/var/log/world"
  keep       = 3
  compressed = true

  [[logger.journal]]
  type = "memory"

  [[logger.journal]]
  type = "file"

  [[logger.journal]]
  type = "syslog"

[monitor]
address  = "127.0.0.1:8001"
location = "/monitor/"

  [monitor.token]
  method = "hs256"
  secret = "helloworld"
  issuer = "foobar.org"
  ttl    = 14400

  [monitor.get]
  anonymous = true
  enabled   = true
  allow     = ["192.168.67.0/24", "127.0.0.0/8",]
  deny      = ["10.0.0.0/8"]

  [monitor.post]
  anonymous = false
  enabled  = true
  allow    = []
  deny     = [
    "10.0.0.0/8",
    "192.168.67.0/24",
    "127.0.0.0/8",
  ]

  [monitor.delete]
  anonymous = true
  enabled  = false
  allow    = []
  deny     = [
    "10.0.0.0/8",
    "192.168.67.0/24",
    "127.0.0.0/8",
  ]

  [monitor.put]
  anonymous = true
  enabled  = false
  allow    = []
  deny     = [
    "10.0.0.0/8",
    "192.168.67.0/24",
    "127.0.0.0/8",
  ]
